"""empty message

Revision ID: a87c3dae09e6
Revises: 
Create Date: 2022-04-24 16:02:21.162128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87c3dae09e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_nop', sa.Integer(), nullable=True))
        batch_op.drop_column('in_people')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('in_people', sa.INTEGER(), nullable=True))
        batch_op.drop_column('avg_nop')

    # ### end Alembic commands ###
